version: "3.8"

name: "orchestra"

services:
  traefik:
    # container_name: traefik
    image: public.ecr.aws/docker/library/traefik:v2.9
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --providers.docker.exposedbydefault=false --entryPoints.web.address=":80"

  whoami-1:
    # container_name: whoami-1
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=PathPrefix(`/`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    environment:
      WHOAMI_NAME: OrchestraSample-1
